export const TRAER_USUARIO = "TRAER_USUARIO"
export const CARGANDO = "CARGANDO"
export const ERROR2 = "ERROR2"
export const TRAER_PERFIL = "TRAER_PERFIL"
export const NO_CARGANDO = "NO_CARGANDO"
export const ROLES_USER = "ROLES_USER"
export const ISLOAD = "ISLOAD"
export const APELLIDO1 = "APELLIDO1"
export const NOISLOAD = "NOISLOAD"
export const TRAER_DEPORTISTAS = "TRAER_DEPORTISTAS"
export const RESET_USER = "RESET_USER"
export const RESET_ROLES = "RESET_ROLES"
export const TRAER_LIQUIDACIONES = "TRAER_LIQUIDACIONES"
export const CSRF_TOKEN = "CSRF_TOKEN"
export const TOKEN = "TOKEN"
export const LOGOUT_TOKEN = "LOGOUT_TOKEN"
export const UID = "UID"
export const CLUB_ID_ENCARGADO = "CLUB_ID_ENCARGADO"
export const CLUB_ID = "CLUB_ID"
export const STATUS = "STATUS"
export const RESET_STATUS = "RESET_STATUS"
export const RESET_PERFIL_BYCLUB = "RESET_PERFIL_BYCLUB"
export const PERFIL_BYCLUB = "PERFIL_BYCLUB"
export const NOMBRE = "NOMBRE"



