export const TRAER_NOTICIAS = "TRAER_NOTICIAS"
export const CARGANDO = "CARGANDO"
export const ERROR2 = "ERROR2"
export const TRAER_DETALLE_NOTICIAS = "TRAER_DETALLE_NOTICIAS"
export const NO_CARGANDO = "NO_CARGANDO"
export const RESET_DETALLE_NOTICIA = "RESET_DETALLE_NOTICIA"
export const TRAER_CATEGORIAS = "TRAER_CATEGORIAS"
export const TRAER_ETIQUETAS = "TRAER_ETIQUETAS"


